[project]
name = "led-cube"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "matplotlib>=3.10.6",
    "numpy>=2.3.2",
    "panda3d>=1.10.15",
    "pytk>=0.0.2.1",
]
